CREATE TRIGGER CALCULATE_NUMBER_OF_STUDENT
ON STUDENT
FOR INSERT, UPDATE, DELETE
AS 
BEGIN
	UPDATE ROOM
	SET NumberOfStudent = (SELECT COUNT(s.RollNumber) FROM STUDENT s WHERE ID = RoomID)
END
		